# server port
server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: akshay
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

