spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password: akshay
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # kafka configuration
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.akshay.payment.notification.PaymentNotificationRequest
server:
  port: 8085

application:
  config:
    product-url: http://localhost:8083/api/products
